### ISSUE TITLE
Crash on 0.17.35 update

### ISSUE THREAD

**Issue by minyan** [smcpeak/factorio-robotank#2]
Log :  
 550.407 Script @__RoboTank__/control.lua:163: Player character 33 has entered vehicle 20043.
 556.040 Script @__RoboTank__/control.lua:163: Player character 33 has exited a vehicle.
 556.040 Error MainLoop.cpp:1173: Exception at tick 410399: The mod RoboTank caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RoboTank::on_player_driving_changed_state (ID 26)
__RoboTank__/control.lua:1865: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__RoboTank__/control.lua:1865: in function <__RoboTank__/control.lua:1834>

**Comment by smcpeak** [comment]
I haven't reproduced this, but I attempted a blind fix based on the crash report.  Please try RoboTank_1.1.1, just uploaded to github and the mod portal, and let me know if it resolves the problem.

**Comment by smcpeak** [comment]
Having not heard back, I'm closing this as presumed fixed.  Reopen if problem persists.
